#!/bin/bash
# Create or update RESUME.md for session handoff
# Usage: ./create-handoff.sh
#
# Run this BEFORE context fills up to prepare for a clean session switch.
# Based on: https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents

set -e

TIMESTAMP=$(date "+%Y-%m-%d %H:%M")
DATE=$(date +%Y-%m-%d)

echo "=== Creating Session Handoff ==="
echo ""

# Check if planning files exist
MISSING_FILES=0
for file in task_plan.md findings.md progress.md; do
    if [ ! -f "$file" ]; then
        echo "⚠ Missing: $file"
        MISSING_FILES=1
    fi
done

if [ $MISSING_FILES -eq 1 ]; then
    echo ""
    echo "Warning: Some planning files are missing."
    echo "The handoff may be incomplete."
    echo ""
fi

# Extract current phase from task_plan.md
CURRENT_PHASE="unknown"
TOTAL_PHASES="unknown"
if [ -f "task_plan.md" ]; then
    CURRENT_PHASE=$(grep -E "^## Current Phase" -A1 task_plan.md | tail -1 | tr -d ' ' || echo "unknown")
    TOTAL_PHASES=$(grep -c "^### Phase" task_plan.md 2>/dev/null || echo "unknown")
fi

# Create RESUME.md
cat > RESUME.md << HEREDOC
# Session Resumption

**Generated:** $TIMESTAMP

## Ready-to-Use Prompt

Copy and paste this into a **new Claude session**:

\`\`\`
Read the following files to restore context and continue execution:
- task_plan.md (phases and progress)
- findings.md (research and decisions)
- progress.md (session log)

Resume from $CURRENT_PHASE. Do not re-do completed work.
\`\`\`

## Session Snapshot

| Field | Value |
|-------|-------|
| **Last Updated** | $TIMESTAMP |
| **Current Phase** | $CURRENT_PHASE of $TOTAL_PHASES |
| **Context Usage** | CHECK WITH /context |

## Volatile Context

<!-- Add anything important that's NOT in the planning files -->

- [ ] 

## Next Action

<!-- What exactly should the next session do first? -->

[UPDATE THIS BEFORE SWITCHING SESSIONS]

## Git Checkpoint

Before switching sessions:

\`\`\`bash
git add task_plan.md findings.md progress.md RESUME.md
git commit -m "checkpoint: $CURRENT_PHASE complete, switching sessions"
\`\`\`

- [ ] Planning files updated
- [ ] Changes committed
- [ ] Ready to switch sessions

---
*Generated by create-handoff.sh — Update the volatile context and next action before switching.*
HEREDOC

echo "✓ Created RESUME.md"
echo ""
echo "Current Phase: $CURRENT_PHASE of $TOTAL_PHASES"
echo ""
echo "NEXT STEPS:"
echo "1. Update RESUME.md with volatile context and next action"
echo "2. Run: git add -A && git commit -m 'checkpoint: session handoff'"
echo "3. Start new Claude session"
echo "4. Paste the prompt from RESUME.md"
echo ""
